# Generated by Django 5.1.5 on 2025-01-30 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='razorpay_payout_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
