# Generated by Django 5.1.5 on 2025-02-06 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locksmiths', '0003_locksmithservice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locksmithprofile',
            name='location',
        ),
        migrations.AddField(
            model_name='locksmithprofile',
            name='location_latitude',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='locksmithprofile',
            name='location_longitude',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='locksmithprofile',
            name='service_radius_km',
            field=models.IntegerField(default=10),
        ),
    ]
